spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://34.148.113.182:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Classof92$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false